config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Global subscriptions view
get 'subscriptions/all', to: 'subscriptions#all', as: 'subscriptions_all'

resources :projects do
  get 'subscriptions/:id/time_entries', to: 'subscriptions#time_entries'
  resources :subscriptions do
    resources :extra_times
  end
end

app/models/ttm/subscription.rb
module TTM

  class TTM::Subscription < ActiveRecord::Base
    has_many :extra_times, class_name: 'TTM::ExtraTime'
    belongs_to :project
    belongs_to :user
    belongs_to :activity, :class_name => 'TimeEntryActivity', optional: true
    belongs_to :tracker, optional: true

    validates_numericality_of :rate, allow_nil: false
    validates_numericality_of :hours, allow_nil: false
    validates :project, presence: true
    validates :activity, presence: true
    validates :tracker, presence: true
    validates_associated :activity
    validate :only_one_subscription_on_period, :begindate_before_enddate

    #after_initialize do |s|
    #  s.calculate_spent
    #end
    def spent
      @spent ||= calculate_spent
      @spent.round(2)
    end

    def hours_with_extra
      @hours_with_extra ||= hours + extra_times.sum(:hours)
      @hours_with_extra
    end

    def left
      l = hours_with_extra - spent
      #l >= 0.0? l : 0.0
      l
    end
    
    def self.active(tracker_id=nil)
      subs = where("begindate <= :today AND enddate >= :today", {today: Date.today}).select { |x| x.status == 'active' || x.status == 'usedup' }
      subs = subs.select {|s| s.tracker_id == tracker_id } if tracker_id
      subs
    end

    def status
      return 'pending' if Date.today < begindate
      return 'closed' if Date.today > enddate
      return 'usedup' if spent >= hours_with_extra
      return 'active'
    end

    def find_time_entries(query_begin, query_end)
      cond = project.project_condition(Setting.display_subprojects_issues?)
      @time_entries = TimeEntry.visible.where(cond).where(activity: activity).where(spent_on: query_begin..query_end).includes(:issue)
    end

    def find_extra_times(query_begin, query_end)
      @extra_times = self.extra_times.where(date_added: query_begin..query_end)
    end

    def calculate_spent
      cond = project.project_condition(Setting.display_subprojects_issues?)
      TimeEntry.visible.where(cond).where(activity: activity).where(spent_on: begindate..enddate).sum(:hours).to_f
    end

    def only_one_subscription_on_period
      possible_overlaps = TTM::Subscription.where(project: project, activity: activity).where("begindate <= ? OR enddate >= ?", enddate, begindate)
      possible_overlaps = possible_overlaps.where("id != ?", id) if id
      possible_overlaps.each { |p|
        if ((p.begindate)..(p.enddate)).overlaps?(begindate..enddate)
          errors.add(:begindate, I18n.t('activerecord.models.subscription.errors.overlap'))
          errors.add(:enddate, I18n.t('activerecord.models.subscription.errors.overlap'))
          errors.add(:activity, I18n.t('activerecord.models.subscription.errors.overlap'))
          break
        end
      }
    end

    def begindate_before_enddate
      errors.add(:begindate, I18n.t('activerecord.models.subscription.errors.begindate')) if begindate > enddate
    end

  end
end

app/controllers/admin/subscriptions_controller.rb
module Admin
  class SubscriptionsController < ApplicationController
    before_action :require_admin
    before_action :set_filters

    def index
      @subscriptions = TTM::Subscription.includes(:project, :activity, :tracker).order('projects.name, subscriptions.subscription_number')

      # Apply filters
      @subscriptions = @subscriptions.where(project_id: @project_id) if @project_id.present?
      @subscriptions = @subscriptions.where('subscriptions.subscription_number LIKE ?', "%#{@search}%") if @search.present?

      # Group by project
      @grouped_subscriptions = @subscriptions.group_by(&:project)
    end

    private

    def require_admin
      unless User.current.admin?
        render_403
      end
    end

    def set_filters
      @project_id = params[:project_id]
      @search = params[:search]
      @projects = Project.visible.order(:name)
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :find_project_by_project_id, except: [:all]
  before_action :authorize, except: [:all]
  before_action :find_subscription, only: [:show, :update, :edit, :destroy, :time_entries]
  before_action :check_all_permission, only: [:all]
  #before_action :find_subscriptions

  accept_api_auth :index, :show, :create, :update, :destroy, :time_entries

  helper :sort
  include SortHelper

  def all
    sort_init 'id', 'asc'
    sort_update 'id' => "#{TTM::Subscription.table_name}.id",
                'name' => "#{TTM::Subscription.table_name}.name",
                'project' => "#{Project.table_name}.name"

    @subscriptions = TTM::Subscription.includes(:project, :activity, :tracker).order(sort_clause)

    @limit = per_page_option
    @subscription_count = @subscriptions.count
    @subscription_pages = Paginator.new @subscription_count, @limit, params[:page]
    @offset ||= @subscription_pages.offset

    if @subscription_count > 0
      @subscriptions = @subscriptions.offset(@offset).limit(@limit)
    end

    respond_to do |format|
      format.html
      format.json { render json: @subscriptions }
    end
  end

  def index

    @query = params[:query]

    if @query
      if params[:search_fild] == 'name'
        @subscriptions = @project.subscriptions.where('`name` LIKE ?', "%#{@query}%")
      end
    else
      @subscriptions = @project.subscriptions
    end

    respond_to do |format|
      format.html
      format.json { render json: @subscriptions }
      format.pdf
    end
  end
  
  def new
    @subscription = TTM::Subscription.new(project: @project, begindate: Date.today, enddate: Date.today + 1.month)
  end

  def edit
  end

  def show
    @query_begin = params["query_begin"]? Date.parse(params["query_begin"]) : Time.now.beginning_of_month.to_date
    @query_end = params["query_end"]? Date.parse(params["query_end"]) : Date.today
    @query_begin = @subscription.begindate.to_date if @query_begin < @subscription.begindate
    @query_end = @subscription.enddate.to_date if @query_end > @subscription.enddate
    @time_entries = @subscription.find_time_entries(@query_begin, @query_end)
    @extra_times = @subscription.find_extra_times(@query_begin, @query_end)
    @total_time = @time_entries.inject(0.0) do |total, te|
          total += te.hours
    end
    @total_cost = @total_time * @subscription.rate
    respond_to do |format|
      format.html
      format.json { render json: @subscription }
    end
  end

  def time_entries
    @query_begin = params["query_begin"]? Date.parse(params["query_begin"]) : Time.now.beginning_of_month.to_date
    @query_end = params["query_end"]? Date.parse(params["query_end"]) : Date.today
    @query_begin = @subscription.begindate.to_date if @query_begin < @subscription.begindate
    @query_end = @subscription.enddate.to_date if @query_end > @subscription.enddate
    @time_entries = @subscription.find_time_entries(@query_begin, @query_end)
    respond_to do |format|
      format.json { render json: @time_entries }
    end
  end

  def destroy
    respond_to do |format|
      if @subscription.delete 
        format.html { redirect_to project_subscriptions_path(@project), notice: t('notice.subscriptions.delete.success') }
        format.json { render text: '', status: :accepted, layout: nil }
      else
        format.html { redirect_to project_subscriptions_path(@project) }
        format.json { render text: '', status: :bad_request, layout: nil }
      end
    end
  end


  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
         format.html { redirect_to project_subscriptions_path(@project), notice: t('notice.subscriptions.update.success') }
         format.json { render text: '', status: :accepted, layout: nil }
       else
         format.html { render action: 'edit'}
         format.json { render text: '', status: :bad_request, layout: nil }
       end
     end
  end

  def create
    @subscription = TTM::Subscription.new(subscription_params)
    @subscription.project = @project
    respond_to do |format|
      if @subscription.save
        format.html { redirect_to project_subscriptions_path(@project), notice: t('notice.subscriptions.create.success') }
        format.json { render text: '', status: :created, layout: nil }
      else
        format.html { render action: 'new' }
        format.json { render text: '', status: :bad_request, layout: nil }
      end
    end
  end

  private

  def check_all_permission
    unless User.current.allowed_to?({ :controller => 'subscriptions', :action => 'all' }, nil, :global => true)
      render_403
    end
  end

  def subscription_params
    params.require(:ttm_subscription).permit(:hours, :activity_id, :tracker_id, :begindate, :enddate, :rate, :name, :notify_email)
  end

  def find_subscription
    @subscription = TTM::Subscription.find(params[:id])
    unless @subscription.project_id == @project.id
      redirect_to project_subscriptions_path(@project), notice: t('notice.subscriptions.not_found')
    end
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  include Redmine::Export::PDF
  include Redmine::Export::PDF::IssuesPdfHelper

  def key_types
    [[t('activerecord.models.password'),'Vault::Password'], [t('activerecord.models.key_file'),'Vault::KeyFile']]
  end

  def subscriptions_to_pdf(subscriptions, project, query)
    pdf = ITCPDF.new(current_language, "L")
    title = "#{project}"
    pdf.set_title(title)
    pdf.alias_nb_pages
    pdf.footer_date = format_date(Date.today)
    pdf.set_auto_page_break(false)
    pdf.add_page("L")

    # Landscape A4 = 210 x 297 mm
    page_height   = pdf.get_page_height # 210
    page_width    = pdf.get_page_width  # 297
    left_margin   = pdf.get_original_margins['left'] # 10
    right_margin  = pdf.get_original_margins['right'] # 10
    bottom_margin = pdf.get_footer_margin
    row_height    = 4

    # column widths
    table_width = page_width - right_margin - left_margin

    # title
    pdf.SetFontStyle('B',11)
    pdf.RDMCell(190,10, title)
    pdf.ln

    pdf.RDMMultiCell(100,row_height,t('activerecord.models.subscription.name'),1,"",0,0)
    pdf.RDMMultiCell(100,row_height,t('activerecord.models.subscription.hours'),1,"",0,0)
    pdf.RDMMultiCell(30,row_height,t('activerecord.models.subscription.begindate'),1,"",0,0)
    pdf.RDMMultiCell(50,row_height,t('activerecord.models.subscription.enddate'),1,"",0,1)

    pdf.SetFontStyle('',8)

    subscriptions.each { |subscription|
      base_y = pdf.get_y
      subscription.name = "-" if subscription.name == nil
      subscription.hours = "-" if subscription.hours == nil
      subscription.begindate = "-" if subscription.begindate == nil
      subscription.enddate = "-" if subscription.enddate == nil

      pdf.RDMMultiCell(100,row_height,subscription.name.to_s,1,"",0,0)
      pdf.RDMMultiCell(100,row_height,subscription.hours.to_s,1,"",0,0)
      pdf.RDMMultiCell(30,row_height,subscription.begindate.to_s,1,"",0,0)
      pdf.RDMMultiCell(50,row_height,subscription.enddate.to_s,1,"",0,1)

      max_height = 6*row_height
      space_left = page_height - base_y - bottom_margin

      if max_height > space_left
        pdf.add_page("L")
        base_y = pdf.get_y
      end

    }

    pdf.output
  end

end

app/views/subscriptions/_active.html.erb
<% unless project.blank? || project.enabled_modules.find_by_name('subscriptions').blank? %>
<p>
<h3><%= t('subscriptions.active.header') %></h3>
<table>
  <%= (render partial: 'subscriptions/time_left', as: 'subscription', collection: defined?(tracker_id)? project.subscriptions.active(tracker_id) : project.subscriptions.active , spacer_template: 'subscriptions/time_left_spacer') || t('subscriptions.active.none') %>
</table>
</p>
<% end %>

app/views/subscriptions/_errors.erb
<% if subscription.errors.any? %>
  <div>
    <h2><%=t('notice.errors')%></h2>
    <ul>
      <% subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/subscriptions/_extra_time.erb
<tr class='<%= extra_time_counter.even? ? 'even':'odd'%>'>
  <td style="text-align:right"><%= extra_time.hours.round(2) %></td>
  <td><%= extra_time.date_added.to_date %></td>
  <% if User.current.allowed_to?(:edit_subscriptions, @project) %>
    <td style="text-align:center">
      <%= link_to '', project_subscription_extra_time_path(@project, @subscription, extra_time), method: :delete, data: { confirm: 'Are you sure?' }, class: 'icon icon-del' %>
    </td>
  <% end %>
</tr>

app/views/subscriptions/_subscription.html.erb
<tr class='<%= subscription_counter.even? ? 'even':'odd'%> <%="subscription-status-#{subscription.status}"%>'>

  <td class=<%="subscription_#{subscription.status}"%>> <i class="fa fa-circle" aria-hidden="true"></i> </td>
  <td><small style="color: #999;"><strong><%= subscription.id %></strong></small></td>
  <td> <%= link_to subscription.name, project_subscription_path(@project, subscription) %> </td>
  <td> <span class="icon icon-time"><%= link_to subscription.hours_with_extra, project_subscription_path(@project, subscription) %></span> </td>
  <td> <span class="icon icon-time"><%= link_to subscription.spent, project_subscription_path(@project, subscription) %></span> </td>
  <td> <%= link_to subscription.begindate.to_date, project_subscription_path(@project, subscription) %> </td>
  <td> <%= link_to subscription.enddate.to_date, project_subscription_path(@project, subscription) %> </td>
  <td> <%= subscription.rate.to_s %> </td>

  <% if User.current.allowed_to?(:edit_subscriptions, @project) %>
    <td>
      <%= link_to '<i class="fa fa-plus-square mr-5" aria-hidden="true"></i>'.html_safe, new_project_subscription_extra_time_path(@project,subscription) %>  &nbsp;
      <%= link_to '<i class="fa fa-pencil-square mr-5" aria-hidden="true"></i>'.html_safe, edit_project_subscription_path(@project,subscription) %>  &nbsp;
      <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, project_subscription_path(@project,subscription), data: {confirm: t('notice.subscriptions.delete.confirm')}, method: :delete %>
    </td>
  <% end %>
</tr>

app/views/subscriptions/_time_entry.html.erb
<tr class='<%= time_entry_counter.even? ? 'even':'odd' %>'>
  <td><%= link_to time_entry.issue, issue_path(time_entry.issue) if time_entry.issue_id %></td>
  <td><%= format_date(time_entry.spent_on) %></td>
  <td><%= time_entry.comments %></td>
  <td style="text-align:right"><%= time_entry.hours.round(2) %></td>
  <td style="text-align:right"><%= number_to_currency((time_entry.hours * @subscription.rate).round(2), unit: Setting.plugin_ttm['ttm_currency'], separator: '.', delimiter: ',') %></td>
</tr>

app/views/subscriptions/all.html.erb
<% html_title(t('activerecord.models.subscriptions')) %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag "font-awesome.css", :plugin => "ttm" %>
  <%= stylesheet_link_tag "font-awesome.min.css", :plugin => "ttm" %>
  <%= stylesheet_link_tag 'ttm', :plugin => 'ttm' %>
<% end %>

<div class="contextual">
</div>

<h2><%= t('activerecord.models.subscriptions') %></h2>

<%= form_tag({}) do %>
<table class='list' id='subscriptions_table'>
  <thead>
  <tr>
    <th style="padding: 4px;">
      <%= text_field_tag(:filter_project, '',
        { id: 'filter-project', class: 'filter-text', placeholder: t('field_project'), style: 'width: 100%; box-sizing: border-box; padding: 4px; border: 1px solid #ddd;' }) %>
    </th>
    <th style="padding: 4px;">
      <%= text_field_tag(:filter_id, '',
        { id: 'filter-id', class: 'filter-text', placeholder: 'ID', style: 'width: 100%; box-sizing: border-box; padding: 4px; border: 1px solid #ddd;' }) %>
    </th>
    <th style="padding: 4px;">
      <%= text_field_tag(:filter_name, '',
        { id: 'filter-name', class: 'filter-text', placeholder: t('activerecord.models.subscription.name'), style: 'width: 100%; box-sizing: border-box; padding: 4px; border: 1px solid #ddd;' }) %>
    </th>
    <th style="padding: 4px;">
      <%= text_field_tag(:filter_activity, '',
        { id: 'filter-activity', class: 'filter-text', placeholder: t('field_activity'), style: 'width: 100%; box-sizing: border-box; padding: 4px; border: 1px solid #ddd;' }) %>
    </th>
    <th style="padding: 4px;">
      <%= text_field_tag(:filter_tracker, '',
        { id: 'filter-tracker', class: 'filter-text', placeholder: t('field_tracker'), style: 'width: 100%; box-sizing: border-box; padding: 4px; border: 1px solid #ddd;' }) %>
    </th>
    <th style="padding: 4px;">
      <%= text_field_tag(:filter_status, '',
        { id: 'filter-status', class: 'filter-text', placeholder: t('activerecord.models.subscription.status'), style: 'width: 100%; box-sizing: border-box; padding: 4px; border: 1px solid #ddd;' }) %>
    </th>
    <th><%= t('activerecord.models.subscription.hours') %></th>
    <th><%= t('subscriptions.index.label.spent') %></th>
    <th><%= t('activerecord.models.subscription.rate') %> (<%=Setting.plugin_ttm['ttm_currency'] %>)</th>
    <th><%= t('subscriptions.index.label.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @subscriptions.each do |subscription| %>
    <tr class='<%= cycle('odd', 'even') %> <%= "subscription-status-#{subscription.status}" %>'>
      <td><%= subscription.project.name %></td>
      <td><strong><%= link_to subscription.id, project_subscription_path(subscription.project, subscription) %></strong></td>
      <td><%= link_to subscription.name, project_subscription_path(subscription.project, subscription) %></td>
      <td><%= subscription.activity&.name || '-' %></td>
      <td><%= subscription.tracker&.name || '-' %></td>
      <td>
        <span class="badge <%= subscription.status %>">
          <%= t("activerecord.models.subscription.statuses.#{subscription.status}") %>
        </span>
      </td>
      <td style="text-align: right;"><%= subscription.hours_with_extra %></td>
      <td style="text-align: right;"><%= subscription.spent %></td>
      <td style="text-align: right;"><%= number_to_currency(subscription.rate, unit: Setting.plugin_ttm['ttm_currency'], separator: '.', delimiter: ',') %></td>
      <td>
        <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, project_subscription_path(subscription.project, subscription), title: t('button_show') %>
        <%= link_to '<i class="fa fa-pencil-square mr-5" aria-hidden="true"></i>'.html_safe, edit_project_subscription_path(subscription.project, subscription), title: t('button_edit') if User.current.allowed_to?(:edit_subscriptions, subscription.project) %>
        <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, project_subscription_path(subscription.project, subscription), method: :delete, data: {confirm: t('notice.subscriptions.delete.confirm')}, title: t('button_delete') if User.current.allowed_to?(:edit_subscriptions, subscription.project) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<span class='pagination'>
  <%= pagination_links_full @subscription_pages, @subscription_count %>
</span>

<% content_for :sidebar do %>
  <h3><%= t('label_filter') %></h3>
  <div class="box">
    <p><strong><%= t('label_total') %>:</strong> <%= @subscription_count %></p>
  </div>
<% end %>

<script type="text/javascript">
  // Client-side filtering for all columns (case-insensitive)
  function applyFilters() {
    var filters = {
      'filter-project': { selector: 'td:nth-child(1)', value: '' },
      'filter-id': { selector: 'td:nth-child(2)', value: '' },
      'filter-name': { selector: 'td:nth-child(3)', value: '' },
      'filter-activity': { selector: 'td:nth-child(4)', value: '' },
      'filter-tracker': { selector: 'td:nth-child(5)', value: '' },
      'filter-status': { selector: 'td:nth-child(6)', value: '' }
    };

    // Get all filter values
    Object.keys(filters).forEach(function(filterId) {
      var elem = document.getElementById(filterId);
      if (elem) {
        filters[filterId].value = elem.value.toLowerCase().trim();
      }
    });

    var rows = document.querySelectorAll('table.list tbody tr');
    rows.forEach(function(row) {
      var matches = true;

      // Check each filter
      Object.keys(filters).forEach(function(filterId) {
        var filter = filters[filterId];
        if (filter.value) {
          var cell = row.querySelector(filter.selector);
          var text = cell ? cell.innerText.toLowerCase().trim() : '';
          if (!text.includes(filter.value)) {
            matches = false;
          }
        }
      });

      row.style.display = matches ? '' : 'none';
    });
  }

  // Add event listeners to all filter fields
  ['filter-project', 'filter-id', 'filter-name', 'filter-activity', 'filter-tracker', 'filter-status'].forEach(function(filterId) {
    var elem = document.getElementById(filterId);
    if (elem) {
      elem.addEventListener('input', applyFilters);
    }
  });
</script>

app/views/subscriptions/index.pdf.erb
<%= raw subscriptions_to_pdf(@subscriptions, @project, @query) %>

app/views/subscriptions/show.html.erb
<div class="contextual">
  <%= link_to t('btn.edit'), edit_project_subscription_path(@project, @subscription), class: 'icon icon-edit' if User.current.allowed_to?(:edit_subscriptions, @project) %>
  <%= link_to t('btn.delete'), project_subscription_path(@project, @subscription), method: :delete, data: { confirm: t('subscriptions.show.delete_confirm') }, class: 'icon icon-del' if User.current.allowed_to?(:edit_subscriptions, @project) %>
  <%= link_to t('button_back'), project_subscriptions_path(@project), class: 'icon icon-back' %>
</div>

<div style="display: flex; align-items: center; gap: 20px; margin-bottom: 15px;">
  <h2 style="margin: 0;"><%= @subscription.name || t('subscriptions.show.header') %></h2>
  <span style="background-color: #e8f4f8; padding: 5px 10px; border-radius: 3px; font-family: monospace; font-size: 0.9em;">
    ID: <%= @subscription.id %>
  </span>
</div>

<div class="splitcontent">
  <div class="splitcontentleft">
    <div class="box">
      <table class="attributes">
        <tr>
          <td class="label"><strong><%= t('field_activity') %></strong></td>
          <td class="value"><%= @subscription.activity&.name || '-' %></td>
          <td class="label"><strong><%= t('field_tracker') %></strong></td>
          <td class="value"><%= @subscription.tracker&.name || '-' %></td>
        </tr>
        <tr>
          <td class="label"><strong><%= t('activerecord.models.subscription.begindate') %></strong></td>
          <td class="value"><%= @subscription.begindate.to_date %></td>
          <td class="label"><strong><%= t('activerecord.models.subscription.enddate') %></strong></td>
          <td class="value"><%= @subscription.enddate.to_date %></td>
        </tr>
        <tr>
          <td class="label"><strong><%= t('activerecord.models.subscription.time') %></strong></td>
          <td class="value"><%= @subscription.hours %> <%= t('activerecord.models.extra_time.hours') %></td>
          <td class="label"><strong><%= t('activerecord.models.subscription.time_with_extra') %></strong></td>
          <td class="value"><%= @subscription.hours_with_extra %> <%= t('activerecord.models.extra_time.hours') %></td>
        </tr>
        <tr>
          <td class="label"><strong><%= t('activerecord.models.subscription.rate') %> (<%=Setting.plugin_ttm['ttm_currency'] %>)</strong></td>
          <td class="value"><%= number_to_currency(@subscription.rate, unit: Setting.plugin_ttm['ttm_currency'], separator: '.', delimiter: ',') %></td>
          <td class="label"><strong><%= t('activerecord.models.subscription.status') %></strong></td>
          <td class="value">
            <span class="badge <%= @subscription.status %>">
              <%= t("activerecord.models.subscription.statuses.#{@subscription.status}") %>
            </span>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="splitcontentright">
    <div class="box">
      <h3><%=t('subscriptions.show.stats_for')%></h3>
      <%= form_tag({ controller: :subscriptions, action: :show }, method: 'get', class: 'box-form') do %>
        <div class="field-row" style="display: flex; gap: 15px; align-items: flex-end;">
          <div class="field" style="flex: 1;">
            <label><%= t('activerecord.models.subscription.begindate') %></label>
            <%= date_field_tag(:query_begin, @query_begin, style: 'width: 100%;') %>
          </div>
          <div class="field" style="flex: 1;">
            <label><%= t('activerecord.models.subscription.enddate') %></label>
            <%= date_field_tag(:query_end, @query_end, style: 'width: 100%;') %>
          </div>
          <div class="field">
            <%= submit_tag(t('button_update'), class: 'btn btn-primary') %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class='splitcontent'>
  <div class='splitcontentleft'>
    <h3><%=t('label_spent_time')%></h3>
    <div class="box tabular">
      <table class='list'>
        <thead>
          <tr>
            <th><%=t('label_issue')%></th>
            <th><%=t('subscriptions.show.date')%></th>
            <th><%=t('subscriptions.show.comment')%></th>
            <th style="text-align:right"><%=t('activerecord.models.subscription.hours')%></th>
            <th style="text-align:right"><%="#{t('subscriptions.show.cost')}, #{Setting.plugin_ttm['ttm_currency']}"%></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: 'time_entry', collection: @time_entries %>
          <% if @time_entries.any? %>
            <tr class="total-row">
              <td colspan="3"><strong><%=t('label_total') %></strong></td>
              <td style="text-align:right"><strong><%= @total_time.round(2) %></strong></td>
              <td style="text-align:right"><strong><%= @total_cost.round(2) %></strong></td>
            </tr>
          <% else %>
            <tr><td colspan="5" class="no-items-text"><%=t('label_no_data')%></td></tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class='splitcontentright'>
    <div class="contextual">
      <%= link_to t('btn.new_extra_time'), new_project_subscription_extra_time_path(@project, @subscription), class: 'icon icon-add' if User.current.allowed_to?(:edit_subscriptions, @project) %>
    </div>
    <h3><%=t('activerecord.models.extra_times')%></h3>
    <div class="box tabular">
      <table class='list'>
        <thead>
          <tr>
            <th style="text-align:right"><%=t('activerecord.models.extra_time.hours')%></th>
            <th><%=t('activerecord.models.extra_time.date_added')%></th>
            <% if User.current.allowed_to?(:edit_subscriptions, @project) %>
              <th style="width: 50px;"></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <%=render partial: 'extra_time', collection: @extra_times %>
          <% if @extra_times.empty? %>
            <tr><td colspan="<%= User.current.allowed_to?(:edit_subscriptions, @project) ? 3 : 2 %>" class="no-items-text"><%=t('label_no_data')%></td></tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>