config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Global subscriptions view
get 'subscriptions/all', to: 'subscriptions#all', as: 'subscriptions_all'

resources :projects do
  get 'subscriptions/:id/time_entries', to: 'subscriptions#time_entries'
  resources :subscriptions do
    resources :extra_times
  end
end

app/models/ttm/subscription.rb
module TTM

  class TTM::Subscription < ActiveRecord::Base
    has_many :extra_times, class_name: 'TTM::ExtraTime'
    belongs_to :project
    belongs_to :user
    belongs_to :activity, :class_name => 'TimeEntryActivity', optional: true
    belongs_to :tracker, optional: true

    validates_numericality_of :rate, allow_nil: false
    validates_numericality_of :hours, allow_nil: false
    validates :project, presence: true
    validates :activity, presence: true
    validates :tracker, presence: true
    validates_associated :activity
    validate :only_one_subscription_on_period, :begindate_before_enddate

    #after_initialize do |s|
    #  s.calculate_spent
    #end
    def spent
      @spent ||= calculate_spent
      @spent.round(2)
    end

    def hours_with_extra
      @hours_with_extra ||= hours + extra_times.sum(:hours)
      @hours_with_extra
    end

    def left
      l = hours_with_extra - spent
      #l >= 0.0? l : 0.0
      l
    end
    
    def self.active(tracker_id=nil)
      subs = where("begindate <= :today AND enddate >= :today", {today: Date.today}).select { |x| x.status == 'active' || x.status == 'usedup' }
      subs = subs.select {|s| s.tracker_id == tracker_id } if tracker_id
      subs
    end

    def status
      return 'pending' if Date.today < begindate
      return 'closed' if Date.today > enddate
      return 'usedup' if spent >= hours_with_extra
      return 'active'
    end

    def find_time_entries(query_begin, query_end)
      cond = project.project_condition(Setting.display_subprojects_issues?)
      @time_entries = TimeEntry.visible.where(cond).where(activity: activity).where(spent_on: query_begin..query_end).includes(:issue)
    end

    def find_extra_times(query_begin, query_end)
      @extra_times = self.extra_times.where(date_added: query_begin..query_end)
    end

    def calculate_spent
      cond = project.project_condition(Setting.display_subprojects_issues?)
      TimeEntry.visible.where(cond).where(activity: activity).where(spent_on: begindate..enddate).sum(:hours).to_f
    end

    def only_one_subscription_on_period
      possible_overlaps = TTM::Subscription.where(project: project, activity: activity).where("begindate <= ? OR enddate >= ?", enddate, begindate)
      possible_overlaps = possible_overlaps.where("id != ?", id) if id
      possible_overlaps.each { |p|
        if ((p.begindate)..(p.enddate)).overlaps?(begindate..enddate)
          errors.add(:begindate, I18n.t('activerecord.models.subscription.errors.overlap'))
          errors.add(:enddate, I18n.t('activerecord.models.subscription.errors.overlap'))
          errors.add(:activity, I18n.t('activerecord.models.subscription.errors.overlap'))
          break
        end
      }
    end

    def begindate_before_enddate
      errors.add(:begindate, I18n.t('activerecord.models.subscription.errors.begindate')) if begindate > enddate
    end

  end
end

app/controllers/admin/subscriptions_controller.rb
module Admin
  class SubscriptionsController < ApplicationController
    before_action :require_admin
    before_action :set_filters

    def index
      @subscriptions = TTM::Subscription.includes(:project, :activity, :tracker).order('projects.name, subscriptions.subscription_number')

      # Apply filters
      @subscriptions = @subscriptions.where(project_id: @project_id) if @project_id.present?
      @subscriptions = @subscriptions.where('subscriptions.subscription_number LIKE ?', "%#{@search}%") if @search.present?

      # Group by project
      @grouped_subscriptions = @subscriptions.group_by(&:project)
    end

    private

    def require_admin
      unless User.current.admin?
        render_403
      end
    end

    def set_filters
      @project_id = params[:project_id]
      @search = params[:search]
      @projects = Project.visible.order(:name)
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :find_project_by_project_id, except: [:all]
  before_action :authorize, except: [:all]
  before_action :find_subscription, only: [:show, :update, :edit, :destroy, :time_entries]
  before_action :check_all_permission, only: [:all]
  #before_action :find_subscriptions

  accept_api_auth :index, :show, :create, :update, :destroy, :time_entries

  helper :sort
  include SortHelper

  def all
    sort_init 'id', 'asc'
    sort_update 'id' => "#{TTM::Subscription.table_name}.id",
                'name' => "#{TTM::Subscription.table_name}.name",
                'project' => "#{Project.table_name}.name"

    @subscriptions = TTM::Subscription.includes(:project, :activity, :tracker).order(sort_clause)

    @limit = per_page_option
    @subscription_count = @subscriptions.count
    @subscription_pages = Paginator.new @subscription_count, @limit, params[:page]
    @offset ||= @subscription_pages.offset

    if @subscription_count > 0
      @subscriptions = @subscriptions.offset(@offset).limit(@limit)
    end

    respond_to do |format|
      format.html
      format.json { render json: @subscriptions }
    end
  end

  def index

    @query = params[:query]

    if @query
      if params[:search_fild] == 'name'
        @subscriptions = @project.subscriptions.where('`name` LIKE ?', "%#{@query}%")
      end
    else
      @subscriptions = @project.subscriptions
    end

    respond_to do |format|
      format.html
      format.json { render json: @subscriptions }
      format.pdf
    end
  end
  
  def new
    @subscription = TTM::Subscription.new(project: @project, begindate: Date.today, enddate: Date.today + 1.month)
  end

  def edit
  end

  def show
    @query_begin = params["query_begin"]? Date.parse(params["query_begin"]) : Time.now.beginning_of_month.to_date
    @query_end = params["query_end"]? Date.parse(params["query_end"]) : Date.today
    @query_begin = @subscription.begindate.to_date if @query_begin < @subscription.begindate
    @query_end = @subscription.enddate.to_date if @query_end > @subscription.enddate
    @time_entries = @subscription.find_time_entries(@query_begin, @query_end)
    @extra_times = @subscription.find_extra_times(@query_begin, @query_end)
    @total_time = @time_entries.inject(0.0) do |total, te|
          total += te.hours
    end
    @total_cost = @total_time * @subscription.rate
    respond_to do |format|
      format.html
      format.json { render json: @subscription }
    end
  end

  def time_entries
    @query_begin = params["query_begin"]? Date.parse(params["query_begin"]) : Time.now.beginning_of_month.to_date
    @query_end = params["query_end"]? Date.parse(params["query_end"]) : Date.today
    @query_begin = @subscription.begindate.to_date if @query_begin < @subscription.begindate
    @query_end = @subscription.enddate.to_date if @query_end > @subscription.enddate
    @time_entries = @subscription.find_time_entries(@query_begin, @query_end)
    respond_to do |format|
      format.json { render json: @time_entries }
    end
  end

  def destroy
    respond_to do |format|
      if @subscription.delete 
        format.html { redirect_to project_subscriptions_path(@project), notice: t('notice.subscriptions.delete.success') }
        format.json { render text: '', status: :accepted, layout: nil }
      else
        format.html { redirect_to project_subscriptions_path(@project) }
        format.json { render text: '', status: :bad_request, layout: nil }
      end
    end
  end


  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
         format.html { redirect_to project_subscriptions_path(@project), notice: t('notice.subscriptions.update.success') }
         format.json { render text: '', status: :accepted, layout: nil }
       else
         format.html { render action: 'edit'}
         format.json { render text: '', status: :bad_request, layout: nil }
       end
     end
  end

  def create
    @subscription = TTM::Subscription.new(subscription_params)
    @subscription.project = @project
    respond_to do |format|
      if @subscription.save
        format.html { redirect_to project_subscriptions_path(@project), notice: t('notice.subscriptions.create.success') }
        format.json { render text: '', status: :created, layout: nil }
      else
        format.html { render action: 'new' }
        format.json { render text: '', status: :bad_request, layout: nil }
      end
    end
  end

  private

  def check_all_permission
    unless User.current.allowed_to?({ :controller => 'subscriptions', :action => 'all' }, nil, :global => true)
      render_403
    end
  end

  def subscription_params
    params.require(:ttm_subscription).permit(:hours, :activity_id, :tracker_id, :begindate, :enddate, :rate, :name, :notify_email)
  end

  def find_subscription
    @subscription = TTM::Subscription.find(params[:id])
    unless @subscription.project_id == @project.id
      redirect_to project_subscriptions_path(@project), notice: t('notice.subscriptions.not_found')
    end
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  include Redmine::Export::PDF
  include Redmine::Export::PDF::IssuesPdfHelper

  def key_types
    [[t('activerecord.models.password'),'Vault::Password'], [t('activerecord.models.key_file'),'Vault::KeyFile']]
  end

  def subscriptions_to_pdf(subscriptions, project, query)
    pdf = ITCPDF.new(current_language, "L")
    title = "#{project}"
    pdf.set_title(title)
    pdf.alias_nb_pages
    pdf.footer_date = format_date(Date.today)
    pdf.set_auto_page_break(false)
    pdf.add_page("L")

    # Landscape A4 = 210 x 297 mm
    page_height   = pdf.get_page_height # 210
    page_width    = pdf.get_page_width  # 297
    left_margin   = pdf.get_original_margins['left'] # 10
    right_margin  = pdf.get_original_margins['right'] # 10
    bottom_margin = pdf.get_footer_margin
    row_height    = 4

    # column widths
    table_width = page_width - right_margin - left_margin

    # title
    pdf.SetFontStyle('B',11)
    pdf.RDMCell(190,10, title)
    pdf.ln

    pdf.RDMMultiCell(100,row_height,t('activerecord.models.subscription.name'),1,"",0,0)
    pdf.RDMMultiCell(100,row_height,t('activerecord.models.subscription.hours'),1,"",0,0)
    pdf.RDMMultiCell(30,row_height,t('activerecord.models.subscription.begindate'),1,"",0,0)
    pdf.RDMMultiCell(50,row_height,t('activerecord.models.subscription.enddate'),1,"",0,1)

    pdf.SetFontStyle('',8)

    subscriptions.each { |subscription|
      base_y = pdf.get_y
      subscription.name = "-" if subscription.name == nil
      subscription.hours = "-" if subscription.hours == nil
      subscription.begindate = "-" if subscription.begindate == nil
      subscription.enddate = "-" if subscription.enddate == nil

      pdf.RDMMultiCell(100,row_height,subscription.name.to_s,1,"",0,0)
      pdf.RDMMultiCell(100,row_height,subscription.hours.to_s,1,"",0,0)
      pdf.RDMMultiCell(30,row_height,subscription.begindate.to_s,1,"",0,0)
      pdf.RDMMultiCell(50,row_height,subscription.enddate.to_s,1,"",0,1)

      max_height = 6*row_height
      space_left = page_height - base_y - bottom_margin

      if max_height > space_left
        pdf.add_page("L")
        base_y = pdf.get_y
      end

    }

    pdf.output
  end

end

app/views/admin/subscriptions/index.html.erb
<div class="contextual">
  <%= link_to t('button_clear'), admin_subscriptions_path, class: 'icon icon-reload' if @project_id.present? || @search.present? %>
</div>

<h2><%= t('admin.ttm.subscriptions.title') %></h2>

<div class="box">
  <%= form_tag(admin_subscriptions_path, method: 'get', class: 'filter-form') do %>
    <div class="field-row" style="display: flex; gap: 15px; align-items: flex-end;">
      <div class="field" style="flex: 1;">
        <label><%= t('field_project') %></label>
        <%= select_tag(:project_id, options_for_select(@projects.map { |p| [p.name, p.id] }, @project_id), { include_blank: t('label_all') }) %>
      </div>
      <div class="field" style="flex: 1;">
        <label><%= t('admin.ttm.subscriptions.search_number') %></label>
        <%= text_field_tag(:search, @search, placeholder: 'SUB-000001') %>
      </div>
      <div class="field">
        <%= submit_tag(t('button_apply'), class: 'btn btn-primary') %>
      </div>
    </div>
  <% end %>
</div>

<% if @grouped_subscriptions.any? %>
  <% @grouped_subscriptions.each do |project, subscriptions| %>
    <div class="box" style="margin-top: 20px;">
      <h3>
        <%= link_to project.name, project_path(project), class: 'project-link' %>
        <span class="count" style="font-size: 12px; color: #999;">(<%= subscriptions.length %> <%= t('admin.ttm.subscriptions.subscriptions') %>)</span>
      </h3>

      <table class="list">
        <thead>
          <tr>
            <th><%= t('admin.ttm.subscriptions.number') %></th>
            <th><%= t('activerecord.models.subscription.name') %></th>
            <th><%= t('field_activity') %></th>
            <th><%= t('activerecord.models.subscription.begindate') %></th>
            <th><%= t('activerecord.models.subscription.enddate') %></th>
            <th style="text-align:right"><%= t('activerecord.models.subscription.time') %></th>
            <th style="text-align:right"><%= t('subscriptions.show.cost') %></th>
            <th><%= t('activerecord.models.subscription.status') %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% subscriptions.each do |sub| %>
            <tr class="<%= cycle('even', 'odd') %>">
              <td><strong><%= sub.subscription_number %></strong></td>
              <td><%= sub.name.present? ? sub.name : "-" %></td>
              <td><%= sub.activity %></td>
              <td><%= sub.begindate.to_date %></td>
              <td><%= sub.enddate.to_date %></td>
              <td style="text-align:right"><%= sub.hours %></td>
              <td style="text-align:right"><%= number_to_currency(sub.rate * sub.hours, unit: Setting.plugin_ttm['ttm_currency'], separator: '.', delimiter: ',') %></td>
              <td>
                <span class="badge <%= sub.status %>">
                  <%= t("activerecord.models.subscription.statuses.#{sub.status}") %>
                </span>
              </td>
              <td style="text-align:center">
                <%= link_to '', project_subscription_path(project, sub), class: 'icon icon-show', title: t('button_view') %>
                <%= link_to '', edit_project_subscription_path(project, sub), class: 'icon icon-edit', title: t('button_edit') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% else %>
  <div class="nodata"><%= t('label_no_data') %></div>
<% end %>